### ISSUE TITLE
Home still not working on deployed demo

### ISSUE THREAD

**Issue by Swiip** [aya-experience/citation#37]
Since #35 the home should work and it has on my computer. Still, http://citation.lux-buisine.fr/ is still broken...

**Comment by mfrachet** [comment]
Maybe helpful : https://github.com/aya-experience/citation/blob/master/citation-demo/src/index.js#L13

Always calling on localhost for graphql call even in "production"

**Comment by Swiip** [comment]
This is wrong indeed but that could not be all. Indeed if the rendering was working well, all data would be preloaded in the page and no request would be needed.

**Comment by Swiip** [comment]
Ok, that was bigger than expected. Most of all, all docker deploy was broken because of some errors on an update of the deploy script. Several fixes on the rendering process, mostly about error management. And finally, it's back online.
